version: '3.8'

services:
  prestashop:
    image: bitnami/prestashop:8.0.1
    # ports:
    #   - 80:80
    environment:
      - PRESTASHOP_FIRST_NAME=${USER_FIRST_NAME}
      - PRESTASHOP_LAST_NAME=${USER_LAST_NAME}
      - PRESTASHOP_EMAIL=${PRESTASHOP_ACCESS_EMAIL}
      - PRESTASHOP_PASSWORD=${PRESTASHOP_ACCESS_PASSWORD}
      - PRESTASHOP_HOST=${PRESTASHOP_DOMAIN}
      - PRESTASHOP_ENABLE_HTTPS=yes
      - PRESTASHOP_COUNTRY=${PRESTASHOP_COUNTRY_LANGUAGE}
      - PRESTASHOP_LANGUAGE=${PRESTASHOP_COUNTRY_LANGUAGE}
      - PRESTASHOP_DATABASE_HOST=mysql
      - PRESTASHOP_DATABASE_NAME=${MYSQL_DATABASE}
      - PRESTASHOP_DATABASE_USER=${MYSQL_USER}
      - PRESTASHOP_DATABASE_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - prestashop_data:/bitnami/prestashop
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - frontend-network
      - backend-network

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    # ports:
    #   - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysql --user=${MYSQL_USER} --password=${MYSQL_PASSWORD} -e "SHOW DATABASES;"
      interval: 5s
      timeout: 2s
      retries: 5
    restart: always
    networks:
      - backend-network
    
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - frontend-network
      - backend-network

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ssl_certs_data:/var/lib/https-portal
    environment:
      # DOMAINS: 'localhost -> http://prestashop:8080'
      # STAGE: 'local'
      DOMAINS: '${PRESTASHOP_DOMAIN} -> http://prestashop:8080'
      STAGE: 'production'
    restart: always
    networks: 
      - frontend-network

volumes:
  mysql_data:
  prestashop_data:
  ssl_certs_data:

networks:
  frontend-network:
  backend-network: